### ISSUE TITLE
用Pytorch训练保存模型，在human_play中加载模型报错

### ISSUE THREAD

**Issue by bxdxstu** [junxiaosong/AlphaZero_Gomoku#116]
Traceback (most recent call last):
  File "E:/project/AlphaZero_Gomoku/human_play.py", line 68, in run
    policy_param = pickle.load(open(model_file, 'rb'))
_pickle.UnpicklingError: A load persistent id instruction was encountered,
but no persistent_load function was specified.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:/project/AlphaZero_Gomoku/human_play.py", line 91, in <module>
    run()
  File "E:/project/AlphaZero_Gomoku/human_play.py", line 72, in run
    encoding='bytes')  # To support python3
_pickle.UnpicklingError: A load persistent id instruction was encountered,
but no persistent_load function was specified.

**Comment by littleWangyu** [comment]
pytorch使用的这段上面的代码
